# ==========================================================
#          . .
#    ___   ___  _  _ _  _  __ _  _  _ 
#   / __| / _ \| |/ / || |/ _` || \| |
#  | (_ || (_) | ' <| __ | (_| || .` |    >_
#   \___| \___/|_|\_\_||_|\__,_||_|\_|
#
# ==========================================================

# --- Pencere ve Bölme Numaralandırması ---
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# --- 1. True Color (24-bit) Desteği ---
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "screen-256color"

# --- 2. Status Bar Genel Ayarları ---
set-option -g status-position top
set -g status-style bg="#1e1e2e",fg="#cdd6f4"
set -g status-justify centre

# --- 3. Pane (Bölme) Sınır Renkleri ---
set -g pane-border-style fg="#313244"
set -g pane-active-border-style fg="#cba6f7"

# --- 4. Mesaj ve Komut Satırı Renkleri ---
set -g message-style bg="#1e1e2e",fg="#39ff14",bold

# --- 5. Sol Kısım (Kullanıcı Bilgisi) ---
set -g status-left "#[bg=#89b4fa,fg=#1e1e2e,bold]  #(whoami) #[bg=#1e1e2e,fg=#89b4fa,nobold,nounderscore,noitalics]"
set -g status-left-length 50

# --- 6. Orta Kısım (Pencere Sekmeleri) ---
# İnaktif pencereler
setw -g window-status-format "#[fg=#6c7086]#[bg=#1e1e2e] #I  #W "
# Aktif pencere ve Zoom Göstergesi (Yeşil İkonlu)
setw -g window-status-current-format "#[fg=#1e1e2e]#[bg=#cba6f7]#[nobold]#[fg=#1e1e2e]#[bg=#cba6f7]#[bold] #I  #W #{?window_zoomed_flag,#[fg=#cba6f7]#[bg=#a6e3a1]#[nobold]#[fg=#1e1e2e]#[bg=#a6e3a1]#[bold] 󰊓 #[fg=#a6e3a1]#[bg=#1e1e2e]#[nobold],#[fg=#cba6f7]#[bg=#1e1e2e]#[nobold]}"

# --- 7. Sağ Kısım (Saat ve Tarih) ---
set -g status-right "#[bg=#1e1e2e,fg=#313244]#[bg=#313244,fg=#cdd6f4,bold] 󰥔 %H:%M #[bg=#313244,fg=#a6e3a1,nobold]#[bg=#a6e3a1,fg=#1e1e2e,bold] 󰃭 %d.%m.%Y "
set -g status-right-length 50

# --- 8. Mouse aktif et ---
set -g mouse on

# --- 9. Kopyalama sistem panosuna da gitsin ---
set -g set-clipboard on
